name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 ./src

    - name: Static analysis with Bandit 
      run: |
        bandit -r ./src

    - name: Run tests
      run: |
        # Add commands to run your tests, for example:
        python -m unittest discover -s tests

    - name: Create deployment package
      run: |
        python ./src/create_deployment_package.py
